### ISSUE TITLE
Encoding selection impossible choice

### ISSUE THREAD

**Issue by NeatNit** [eyalroz/bidimailui#119] opened 2024-01-07 05:47 UTC
Soon after installing this addon and using it to write an email, I switched to reading mail and a pop-up asked me something about which non-Unicode encoding to use. It had three options, but **all options were cut off with no way to see what they really are.** The first two options were identical in the part that was visible, and the last option was something like 'don't make a choice'. So between the two real options, if there actually was a reason to care, you'd have to close your eyes and guess.

Unfortunately I didn't take a screenshot, and I don't know how to recreate it since I think it only happens once. I tried to remove and reinstall the extension but the question never showed up again. It might require a fresh installation of Thunderbird to reproduce, I didn't go that far yet.

**Comment by NeatNit** [comment] 2024-01-07 05:51
Ah, these strings are what showed up:
https://github.com/eyalroz/bidimailui/blob/master/src/chrome/locale/en-US/bidimailui.properties
I still don't know how to trigger it, but doing whatever triggers this dialog will get you there.

**Comment by NeatNit** [comment] 2024-01-07 13:55
In case it's relevant: I'm using Linux Mint 21.2 Cinnamon.

**Comment by eyalroz** [comment] 2024-01-12 13:43
> all options were cut off with no way to see what they really are. 

Can you install the extension on a new profile and provide a screenshot?

**Comment by eyalroz** [comment] 2024-08-01 15:07
Noticed, too late, that #122  is a duplicate of this bug; and I've resolved #122, albeit not perfectly. Please try the latest release with TB v128.

The reason for this problem is Thunderbird itself degrading the XUL dialog boxes without providing an alternative :-(

**Closed by eyalroz** 2024-08-01 15:07 UTC

**Comment by NeatNit** [comment] 2024-08-01 15:10
Sorry I didn't reply back then. IIRC I couldn't get it to show up again.

Thank you for resolving this.

**Comment by eyalroz** [comment] 2024-08-01 15:14
Sorry for not being attenative enough when you reported this. I want to encourage you not to give up on filing issues....

**Comment by NeatNit** [comment] 2024-08-01 15:16
No worries, I won't :)
